In [1]:
#numpy library installation
!pip install numpy

In [2]:
#importing the library
import numpy as np

In [3]:
#library version
np.__version__

'1.22.4'

In [4]:
array1 = np.array(11,12,13,14,15)
array1

TypeError: ignored

In [7]:
array1 = np.array([11,12,13,14,15])
array1
#print(array1)

array([11, 12, 13, 14, 15])

In [8]:
array2 = np.array([1,2,3],[4,5,6],[7,8,9])
array2

TypeError: ignored

In [9]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# datatype

In [11]:
array3 = np.array([10,11,12,14])
print(array3)
print(array3.dtype)

[10 11 12 14]
int64


In [12]:
array4 = np.array([10.0,11.3,12.0,14.8])
print(array4)
print(array4.dtype)

[10.  11.3 12.  14.8]
float64


In [14]:
#check for homogeneous - array
array5 = np.array([10,11,12.0,14.8])
array5

array([10. , 11. , 12. , 14.8])

In [15]:
#heterogenous - not possible
array6 = np.array([10,11,12.0,14.8, 'hello'])
array6

array(['10', '11', '12.0', '14.8', 'hello'], dtype='<U32')

In [18]:
#list vs array
array7 = np.arange(20)
array7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
from timeit import default_timer as timer
array8 = np.random.randn(10000)
array9 = np.random.randn(10000)

In [21]:
lista = list(array8)   #converts to list from array format
listb = list(array9)

sample = 10000

def dot1():
  dot =0
  for i in range(len(lista)):
    dot += lista[i] * listb[i]
  return dot

def dot2():
  return np.dot(array8, array9)

start =timer()
for t in range(sample):
  dot1()
end =timer()
t1 = end -start

start =timer()
for t in range(sample):
  dot2()
end =timer()
t2 = end -start

print('computtaion time for list', t1)
print('computtaion time for array', t2)
print('diff', t1/t2)


computtaion time for list 18.95251202700001
computtaion time for array 0.039905501000021104
diff 474.93482231910804


In [22]:
#numpy methods / functions
#just for the reference =
array7 = np.arange(20)
array9 = array7
array9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
#copying the elements / arrays from one variable to other
array10 = array7.copy()
array10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
array11 = np.arange(5)
array11

array([0, 1, 2, 3, 4])

In [27]:
array12 = np.arange(10,30,2)
array12

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [28]:
array13 = np.arange(-10,30,2)
array13

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10,  12,  14,
        16,  18,  20,  22,  24,  26,  28])

In [29]:
array13 = np.arange(-10,30,2.5)
array13

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ,
        12.5,  15. ,  17.5,  20. ,  22.5,  25. ,  27.5])

In [30]:
#memory
print(array13.nbytes)

128


In [31]:
#dimentionality
print(array13.ndim)

1


In [32]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2.ndim)

2


In [33]:
#shape
print(array2.shape)

(3, 3)


In [34]:
#itemsize
print(array2.itemsize)

8


In [35]:
#size
print(array2.size)

9


#Indexing

In [38]:
array_1 = np.arange(20,40)
array_1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [39]:
print(array_1[2])

22


In [42]:
print(array_1[7])

27


In [43]:
print(array_1[5:7])

[25 26]


In [44]:
print(array_1[-1])

39


In [45]:
print(array_1[-1:4])

[]


In [46]:
print(array_1[4:-5])

[24 25 26 27 28 29 30 31 32 33 34]


In [47]:
array_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
print(array_2[0])

[1 2 3]


In [49]:
print(array_2[1,1])

5


In [50]:
print(array_2[-1])

[7 8 9]


In [51]:
print(array_2[1][1])

5


In [52]:
print(array_2[0,1])

2


In [53]:
print(array_2[0,1:-1])

[2]


In [54]:
print(array_2[0,1:-2])

[]


In [55]:
print(array_2[:,1])

[2 5 8]


In [56]:
print(array_2[1,:])

[4 5 6]


In [57]:
print(array_2[1:3,:])

[[4 5 6]
 [7 8 9]]


In [58]:
print(array_2[1:2,:])

[[4 5 6]]


#Slicing

In [59]:
array_1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [60]:
array_1[:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [61]:
array_1[1:5]

array([21, 22, 23, 24])

In [62]:
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
array_2[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
array_2[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [65]:
array_2[2,2]

9

In [66]:
array_2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [72]:
array_2[:2,:2]

array([[1, 2],
       [4, 5]])

#Basic math operation

In [73]:
array_3 = np.array([1,2,2,3,4,5,5,6])
array_4 = np.array([1,2,2,3,4,5,5,6])
array_3 + array_4

array([ 2,  4,  4,  6,  8, 10, 10, 12])

In [74]:
array_3 - array_4

array([0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
array_3 * array_4

array([ 1,  4,  4,  9, 16, 25, 25, 36])

In [76]:
compare_ = array_3 > 2
print(compare_)

[False False False  True  True  True  True  True]


In [77]:
np.add(array_3, array_4)

array([ 2,  4,  4,  6,  8, 10, 10, 12])

In [78]:
np.subtract(array_3, array_4)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [79]:
np.multiply(array_3, array_4)

array([ 1,  4,  4,  9, 16, 25, 25, 36])

In [80]:
np.negative(array_3)

array([-1, -2, -2, -3, -4, -5, -5, -6])

In [82]:
np.concatenate([array_3, array_4])

array([1, 2, 2, 3, 4, 5, 5, 6, 1, 2, 2, 3, 4, 5, 5, 6])

In [85]:
np.concatenate((array_2, array_2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
np.concatenate((array_2, array_2), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
np.concatenate((array_2, array_2), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [88]:
np.concatenate((array_2, array_2), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
array_2 = np.array([[11,2,34],[4,55,6],[7,8,9]])
deter = np.linalg.det(array_2)
print(deter)

-7072.999999999999


In [95]:
np.diag(array_2) #diagnol matrix

array([11, 55,  9])

In [96]:
evalue, evect = np.linalg.eig(array_2) #eigen value, eigen vector

In [97]:
print(evalue)

[-5.31169138 23.39574353 56.91594785]


In [98]:
print(evect)

[[ 0.90186732 -0.9202832  -0.18098572]
 [-0.01686849  0.18220794 -0.96542252]
 [-0.43168366 -0.3462356  -0.18762605]]


In [99]:
np.linalg.inv(array_2) #inverse matrix

array([[-0.06319808, -0.03591121,  0.2626891 ],
       [-0.0008483 ,  0.0196522 , -0.00989679],
       [ 0.0499081 ,  0.01046232, -0.08440549]])