In [1]:
!pip install scipy

In [2]:
import scipy

# List functions in the main scipy module
print("Functions in scipy module:")
print(dir(scipy))

Functions in scipy module:
['LowLevelCallable', '__numpy_version__', '__version__', 'cluster', 'datasets', 'fft', 'fftpack', 'integrate', 'interpolate', 'io', 'linalg', 'misc', 'ndimage', 'odr', 'optimize', 'show_config', 'signal', 'sparse', 'spatial', 'special', 'stats', 'test']


In [3]:
# List functions in a specific sub-package (e.g., linalg)
from scipy import linalg
print("\nFunctions in scipy.linalg sub-package:")
print(dir(linalg))


Functions in scipy.linalg sub-package:
['LinAlgError', 'LinAlgWarning', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_basic', '_cythonized_array_utils', '_decomp', '_decomp_cholesky', '_decomp_cossin', '_decomp_ldl', '_decomp_lu', '_decomp_polar', '_decomp_qr', '_decomp_qz', '_decomp_schur', '_decomp_svd', '_decomp_update', '_expm_frechet', '_fblas', '_flapack', '_flinalg', '_flinalg_py', '_matfuncs', '_matfuncs_expm', '_matfuncs_sqrtm', '_matfuncs_sqrtm_triu', '_misc', '_procrustes', '_sketches', '_solve_toeplitz', '_solvers', '_special_matrices', 'bandwidth', 'basic', 'blas', 'block_diag', 'cdf2rdf', 'cho_factor', 'cho_solve', 'cho_solve_banded', 'cholesky', 'cholesky_banded', 'circulant', 'clarkson_woodruff_transform', 'companion', 'convolution_matrix', 'coshm', 'cosm', 'cossin', 'cython_blas', 'cython_lapack', 'decomp', 'decomp_cholesky', 'decomp_lu', 'decomp_qr', 'decomp_schur', 'decomp_svd', 'de

## Linear Algebra


1. Data Representation: In data science, data is often represented in the form of matrices and vectors. Each row of a matrix can represent an observation, while each column can represent a specific feature or variable. Linear algebra provides the necessary framework for organizing and representing data in a structured and concise manner.

2. Linear Transformations: Many data transformations, such as rotation, scaling, and projection, can be represented as linear transformations. Linear algebra allows data scientists to apply these transformations efficiently using matrix operations, which is especially useful in tasks like feature engineering and dimensionality reduction.

3. Solving Linear Systems: Data science often involves solving systems of linear equations to model relationships between variables or predict outcomes. Linear algebra provides techniques like matrix inversion and solving linear systems, which are used in various data analysis and machine learning algorithms.

4. Eigenvalues and Eigenvectors: Eigenvalues and eigenvectors are crucial concepts in linear algebra used to understand the underlying structure and variance of data. They are used in techniques like principal component analysis (PCA) for dimensionality reduction and feature extraction.

5. Optimization: Data scientists often encounter optimization problems when training machine learning models or finding the best solution to a particular task. Linear algebra techniques, such as gradient descent, help in optimizing parameters to achieve the best model performance.

6. Singular Value Decomposition (SVD): SVD is a powerful linear algebra tool used for data compression, noise reduction, and latent semantic analysis in natural language processing and recommendation systems.

7. Image and Signal Processing: Linear algebra is extensively used in image and signal processing tasks, such as image compression, denoising, and image recognition. Techniques like the discrete Fourier transform (DFT) are based on linear algebra principles.

8. Data Manipulation and Linear Operations: Many data manipulations, such as data filtering, smoothing, and interpolation, can be performed using linear algebra operations like convolution and matrix multiplication.

9. Machine Learning Algorithms: Linear algebra forms the backbone of various machine learning algorithms, including linear regression, support vector machines (SVMs), and neural networks. It allows for efficient computation and model training.

10. Numerical Stability: Linear algebra plays a vital role in ensuring numerical stability and accuracy in data computations. Techniques like LU decomposition and QR decomposition are used to enhance the numerical stability of algorithms.

In [9]:
import numpy as np
from scipy import linalg

# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix addition
C = A + B
print("Matrix Addition:")
print(C)

# Matrix subtraction
D = A - B
print("Matrix Subtraction:")
print(D)

# Scalar multiplication
scalar = 2
E = scalar * A
print("Scalar Multiplication:")
print(E)

Matrix Addition:
[[ 6  8]
 [10 12]]
Matrix Subtraction:
[[-4 -4]
 [-4 -4]]
Scalar Multiplication:
[[2 4]
 [6 8]]


In [10]:
# Solving Linear Systems

import numpy as np
from scipy import linalg

# Example matrix and vector
A = np.array([[2, 1], [3, 4]])
b = np.array([5, 6])

# Solve the linear system Ax = b
x = linalg.solve(A, b)
print("Solution x:")
print(x)


Solution x:
[ 2.8 -0.6]


In [11]:
# 2. Solving a linear system Ax = b
b = np.array([1, 2])
x = linalg.solve(A, b)
print("Solution x:", x)

Solution x: [0.4 0.2]


In [4]:
import numpy as np
from scipy import linalg

# Example matrix
A = np.array([[2, 1], [3, 4]])

# Computing the determinant of a matrix
det_A = linalg.det(A)
print("Determinant of A:", det_A)

# Finding the eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
for i in range(len(eigenvectors)):
    print("Eigenvalue:", eigenvalues[i])
    print("Eigenvector:", eigenvectors[:, i])

Determinant of A: 5.0
Solution x: [0.4 0.2]
Eigenvalues: [1.+0.j 5.+0.j]
Eigenvectors:
Eigenvalue: (1+0j)
Eigenvector: [-0.70710678  0.70710678]
Eigenvalue: (5+0j)
Eigenvector: [-0.31622777 -0.9486833 ]


Matrix inversion is a fundamental operation in linear algebra that involves finding the "inverse" of a square matrix. Given a square matrix A, its inverse, denoted as A^-1, is a new matrix that, when multiplied with A, yields the identity matrix (I). The identity matrix is a special square matrix with ones on the main diagonal and zeros elsewhere.

In [6]:
#Matrix Inversion (scipy.linalg.inv):
import numpy as np
from scipy import linalg

# Example matrix
A = np.array([[2, 1], [3, 4]])
print(A)

# Matrix inversion
A_inv = linalg.inv(A)
print("Inverse of A:")
print(A_inv)

# Verify: A * A_inv should be the identity matrix
identity_matrix = np.dot(A, A_inv)
print("A * A_inv:")
print(identity_matrix)

[[2 1]
 [3 4]]
Inverse of A:
[[ 0.8 -0.2]
 [-0.6  0.4]]
A * A_inv:
[[1. 0.]
 [0. 1.]]


QR decomposition is a matrix factorization technique in linear algebra. It decomposes a matrix A into the product of an orthogonal matrix Q and an upper triangular matrix R. This factorization is widely used in various numerical algorithms, including solving linear systems, least squares problems, and eigenvalue computations

In [13]:
import numpy as np
from scipy import linalg

# Example matrix
A = np.array([[2, 1], [3, 4], [1, 2]])

# Perform QR decomposition
Q, R = linalg.qr(A)

print("Orthogonal matrix Q:")
print(Q)
print("Upper triangular matrix R:")
print(R)

# Verify: Reconstruct A from Q and R
A_reconstructed = np.dot(Q, R)
print("A reconstructed from Q and R:")
print(A_reconstructed)


Orthogonal matrix Q:
[[-0.53452248  0.78039897  0.32444284]
 [-0.80178373 -0.34684399 -0.48666426]
 [-0.26726124 -0.52026598  0.81110711]]
Upper triangular matrix R:
[[-3.74165739 -4.27617987]
 [ 0.         -1.64750894]
 [ 0.          0.        ]]
A reconstructed from Q and R:
[[2. 1.]
 [3. 4.]
 [1. 2.]]


LU decomposition, also known as LU factorization, is a method used to factorize a square matrix A into the product of two triangular matrices: a lower triangular matrix L and an upper triangular matrix U. It is widely used in numerical linear algebra and plays a crucial role in solving systems of linear equations and matrix inversion.

In [7]:
# LU Decomposition (scipy.linalg.lu):
import numpy as np
from scipy import linalg

# Example matrix
A = np.array([[2, 1], [3, 4]])

# LU decomposition
P, L, U = linalg.lu(A)
print("Permutation matrix P:")
print(P)
print("Lower triangular matrix L:")
print(L)
print("Upper triangular matrix U:")
print(U)

# Verify: Reconstruct A from LU decomposition
A_reconstructed = P @ L @ U
print("A reconstructed from LU decomposition:")
print(A_reconstructed)

Permutation matrix P:
[[0. 1.]
 [1. 0.]]
Lower triangular matrix L:
[[1.         0.        ]
 [0.66666667 1.        ]]
Upper triangular matrix U:
[[ 3.          4.        ]
 [ 0.         -1.66666667]]
A reconstructed from LU decomposition:
[[2. 1.]
 [3. 4.]]


Matrix norms are mathematical measures used to determine the "size" or magnitude of a matrix. Similar to vector norms, which quantify the "length" of a vector, matrix norms provide a way to assess the "size" of a matrix in various ways. Different matrix norms are defined based on different properties and have various applications in linear algebra, numerical analysis, and other fields.

In [8]:
# Matrix Norms (scipy.linalg.norm):
import numpy as np
from scipy import linalg

# Example matrix
A = np.array([[1, 2], [3, 4]])

# Matrix norms
frobenius_norm = linalg.norm(A, ord='fro')
print("Frobenius norm of A:", frobenius_norm)

# Other norms
# L1 norm (max column sum)
l1_norm = linalg.norm(A, ord=1)
print("L1 norm of A:", l1_norm)

# L2 norm (max singular value)
l2_norm = linalg.norm(A, ord=2)
print("L2 norm of A:", l2_norm)

Frobenius norm of A: 5.477225575051661
L1 norm of A: 6.0
L2 norm of A: 5.464985704219043


## Optimization

In [15]:
# Finding the Minimum of a Function

import numpy as np
from scipy.optimize import minimize_scalar

# Define the function to minimize
def f(x):
    return x**2 + 5*x + 6

# Use minimize_scalar to find the minimum of the function
result = minimize_scalar(f)

# Extract the minimum value and the corresponding argument
min_value = result.fun
min_arg = result.x

print("Minimum value:", min_value)
print("Argument for minimum value:", min_arg)


Minimum value: -0.25
Argument for minimum value: -2.5


In [16]:
# Optimizing Parameters for Machine Learning Models
import numpy as np
from scipy.optimize import minimize

# Example data for linear regression
X = np.array([1, 2, 3, 4, 5])
y = np.array([3, 5, 7, 9, 11])

# Define the loss function (Mean Squared Error for linear regression)
def loss_function(params):
    predicted_y = params[0] * X + params[1]
    return np.mean((predicted_y - y)**2)

# Use minimize to find the best parameters for linear regression
initial_guess = [1, 0]  # Initial guess for parameters
result = minimize(loss_function, initial_guess)

# Extract the optimized parameters
optimal_params = result.x

print("Optimized parameters:", optimal_params)


Optimized parameters: [1.99999968 1.00000125]


In [17]:
# Global Optimization
import numpy as np
from scipy.optimize import differential_evolution

# Define the function to minimize (Rosenbrock function)
def rosenbrock(x):
    return (1 - x[0])**2 + 100 * (x[1] - x[0]**2)**2

# Use differential_evolution for global optimization
result = differential_evolution(rosenbrock, [(-2, 2), (-2, 2)])

# Extract the global minimum value and arguments
global_min_value = result.fun
global_min_args = result.x

print("Global minimum value:", global_min_value)
print("Arguments for global minimum value:", global_min_args)

Global minimum value: 0.0
Arguments for global minimum value: [1. 1.]
